name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: 오라클 WAS 배포
    runs-on: ubuntu-22.04
    steps:
      - name: git pull
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 129.154.53.117
          port: 22
          username: brokoli
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd www; git pull origin main;"

      - name: install composer
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 129.154.53.117
          port: 22
          username: brokoli
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd www; composer install;"

      - name: db migration
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 129.154.53.117
          port: 22
          username: brokoli
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd www; php8.2 artisan migrate --force;"

      - name: build frontend components
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 129.154.53.117
          port: 22
          username: brokoli
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd www; npm install && npm run build;"

      - name: php-fpm reload
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 129.154.53.117
          port: 22
          username: brokoli
          key: ${{secrets.PRIVATE_KEY}}
          script: "sudo service php8.2-fpm reload;"

